spring:
  application:
    name: broker

  mvc:
    problemdetails:
      enabled: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    table: flyway_schema_history
    group: true
