spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  flyway:
    clean-disabled: false
    validate-on-migrate: false

logging:
  level:
    org.flywaydb: DEBUG
