spring:
  flyway:
    clean-disabled: false
    validate-on-migrate: false

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

app:
  security:
    cookie:
      secure: false

logging:
  level:
    com.pcrm.broker: DEBUG
